name: Build IPQ807x NSS WiFi

on: workflow_dispatch

jobs:
    build:
        name: Prepare and build IPQ807x NSS generic images
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Update and install feeds
              run: |
                ./scripts/feeds update -a
                ./scripts/feeds install -a

            - name: Import and patch .config for 1G + AX6/AX3600
              run: |
                mv .full_config .config

                # 替换内存为1GB
                sed -i 's/CONFIG_ATH11K_MEM_PROFILE_512M=y/# CONFIG_ATH11K_MEM_PROFILE_512M is not set\nCONFIG_ATH11K_MEM_PROFILE_1G=y/' .config
                sed -i 's/CONFIG_IPQ_MEM_PROFILE_512=y/# CONFIG_IPQ_MEM_PROFILE_512 is not set\nCONFIG_IPQ_MEM_PROFILE_1024=y/' .config

                # 只保留 redmi_ax6 与 xiaomi_ax3600
                sed -i 's/.*DEVICE_redmi_ax6.*/CONFIG_TARGET_qualcommax_ipq807x_DEVICE_redmi_ax6=y/' .config
                sed -i 's/.*DEVICE_xiaomi_ax3600.*/CONFIG_TARGET_qualcommax_ipq807x_DEVICE_xiaomi_ax3600=y/' .config
                sed -i '/CONFIG_TARGET_.*_DEVICE_/!b; /ax6\|ax3600/!s/^/# /' .config

                make defconfig

            - name: QoL fixes on default config
              run: |
                mkdir -p files/etc/uci-defaults
                cat > files/etc/uci-defaults/99-qol_fixes << EOF
                uci set wireless.radio0.country='US'
                uci set wireless.radio1.country='US'
                uci set wireless.radio2.country='US'
                uci set wireless.radio1.disabled=0
                uci set wireless.radio2.disabled=0
                uci set pbuf.opt.memory_profile=auto
                uci set firewall.@defaults[0].flow_offloading=0
                uci set ecm.@general[0].enable_bridge_filtering=0
                uci set system.@system[0].cronloglevel='7'
                /etc/init.d/mwan3 stop
                /etc/init.d/mwan3 disable
                /etc/init.d/sqm stop
                /etc/init.d/sqm disable
                uci commit
                EOF

            - name: Download package sources
              run: make download V=s

            - name: Build tools
              run: |
                make tools/install -j$(nproc) V=s || \
                make tools/install V=s

            - name: Build toolchain
              run: |
                make toolchain/install -j$(nproc) V=s || \
                make toolchain/install V=s

            - name: Build target images
              run: |
                make -j$(nproc) V=s || \
                make V=s

            - name: Get the current date
              run: echo "NOW=$(date +%F-%H%M)" >> $GITHUB_ENV

            - name: Create a release
              uses: "ncipollo/release-action@v1"
              with:
                name: "Updated prebuilt images (AX6/AX3600 1G NSS) ${{ env.NOW }}"
                commit: "main_nss"
                tag: "ax6-ax3600-1g-${{ env.NOW }}"
                generateReleaseNotes: true
                makeLatest: true
                artifacts: bin/targets/qualcommax/ipq807x/*
                token: "${{ secrets.GITHUB_TOKEN }}"
